// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIN1we86K--7dD5_jhm0dSU1lUyC0zx0w',
    appId: '1:765566821369:web:8839322c5748b0b63a1328',
    messagingSenderId: '765566821369',
    projectId: 'crudtutorial-a0e3c',
    authDomain: 'crudtutorial-a0e3c.firebaseapp.com',
    storageBucket: 'crudtutorial-a0e3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQAf95pnielHGmBhyA5JxPBdG1KhYNq8',
    appId: '1:765566821369:android:c40b96f7648a1b213a1328',
    messagingSenderId: '765566821369',
    projectId: 'crudtutorial-a0e3c',
    storageBucket: 'crudtutorial-a0e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdKK4BsIXwwU7BjFsMpUv-xIW1ekCNwo',
    appId: '1:765566821369:ios:8f1b8c6fcbae74ad3a1328',
    messagingSenderId: '765566821369',
    projectId: 'crudtutorial-a0e3c',
    storageBucket: 'crudtutorial-a0e3c.appspot.com',
    iosBundleId: 'com.example.crd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdKK4BsIXwwU7BjFsMpUv-xIW1ekCNwo',
    appId: '1:765566821369:ios:f599a014af3477423a1328',
    messagingSenderId: '765566821369',
    projectId: 'crudtutorial-a0e3c',
    storageBucket: 'crudtutorial-a0e3c.appspot.com',
    iosBundleId: 'com.example.crd.RunnerTests',
  );
}
